language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - yarn global add codecov
  - yarn
script:
  - lint-staged
  - yarn run test:ci && codecov
# after_success:
#   - |
#     if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
#       git config --global user.name "Caredoc Design System CI"
#       echo -e "machine github.com\n login react-native-elements-ci\n password $GITHUB_TOKEN" >> ~/.netrc
#       cd website && yarn && GIT_USER=react-native-elements-ci yarn run publish-gh-pages
#     fi
before_deploy: "yarn run compile"
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "dist/**/*"
  skip_cleanup: true
  on:
    tags: true
    repo: @caredoc/design-system
